site_name: HTTPlug Plugins Documentation
site_favicon: favicon.ico
copyright: © 2015 PHP HTTP Team
theme: readthedocs
extra_css:
    - css/extra.css
markdown_extensions:
    - toc:
        permalink: true
    - sane_lists
    - admonition
